packages: []

minimumReleaseAgeExclude: []

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

trustPolicyExclude:
  - undici-types@6.21.0
  - eslint-import-resolver-typescript@3.10.1
  - semver@6.3.1
